# Generated by Django 4.2 on 2025-03-17 13:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=250,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator],
            ),
        ),
    ]
