# Generated by Django 4.2 on 2025-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions",
                related_query_name="custom_user_permissions",
                to="auth.permission",
            ),
        ),
    ]
