# Generated by Django 4.2 on 2025-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_alter_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Permissions",
            field=models.ManyToManyField(
                related_name="users", related_query_name="user", to="auth.permission"
            ),
        ),
    ]
