# Generated by Django 4.2 on 2025-03-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0010_alter_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                related_query_name="user",
                to="auth.permission",
            ),
        ),
    ]
