# Generated by Django 4.2 on 2025-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delivery_provider",
            field=models.BooleanField(default=False),
        ),
    ]
