# Generated by Django 4.2 on 2025-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_is_delivery_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="is_delivery_provider",
            field=models.BooleanField(default=False),
        ),
    ]
