# Generated by Django 4.2 on 2025-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_pendinguser_is_delivery_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
