# Generated by Django 4.2 on 2025-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_pendinguser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
