# Generated by Django 4.2 on 2025-05-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_user_city_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
