# Generated by Django 4.2 on 2025-05-27 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_pendinguser_city_pendinguser_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="pendinguser",
            name="country",
        ),
    ]
