# Generated by Django 4.2 on 2024-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
