# Generated by Django 4.2 on 2024-11-23 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="profile_image",
        ),
    ]
