# Generated by Django 4.2 on 2024-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_remove_customer_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
