# Generated by Django 4.2 on 2025-05-04 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_alter_cart_customer_alter_cartproduct_cart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered", models.BooleanField(default=False)),
                (
                    "delivery_provider",
                    models.ForeignKey(
                        limit_choices_to={"is_delivery_provider": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_assignment",
                        to="cart.purchase",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_assignment",
            },
        ),
    ]
