# Generated by Django 4.2 on 2025-05-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0004_deliveryassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryassignment",
            name="delivery_provider",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_delivery_provider": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
