# Generated by Django 4.2 on 2025-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_deliveryassignment_delivery_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="provider_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
