# Generated by Django 4.2 on 2025-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_deliveryassignment_provider_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
