# Generated by Django 4.2 on 2025-05-11 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_purchase_delivery_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="delivery_location",
        ),
    ]
