# Generated by Django 4.2 on 2025-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_remove_purchase_delivery_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
