# Generated by Django 4.2 on 2025-05-12 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_purchase_latitude_purchase_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="longitude",
        ),
    ]
