# Generated by Django 4.2 on 2025-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_purchase_city_purchase_country_purchase_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price_at_purchase",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
    ]
