# Generated by Django 4.2 on 2024-11-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newgames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("image_path", models.ImageField(upload_to="newgames/")),
                ("description", models.TextField(blank=True, default="")),
                ("video_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "newgames",
            },
        ),
    ]
