# Generated by Django 4.2 on 2024-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newgames", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newgames",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
