# Generated by Django 4.2 on 2024-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newgames", "0004_alter_newgames_game_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="newgames",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="newgames",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
