# Generated by Django 4.2 on 2024-08-17 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_cartitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
