# Generated by Django 4.2 on 2024-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_remove_product_category_alter_product_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image_path",
            field=models.ImageField(blank=True, null=True, upload_to="subcategories/"),
        ),
    ]
