# Generated by Django 4.2 on 2024-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_subcategory_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
