# Generated by Django 4.2 on 2025-02-17 19:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0016_searchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        choices=[
                            (Decimal("1.0"), "1.0 نجمة"),
                            (Decimal("1.5"), "1.5 نجمة"),
                            (Decimal("2.0"), "2.0 نجمة"),
                            (Decimal("2.5"), "2.5 نجمة"),
                            (Decimal("3.0"), "3.0 نجمة"),
                            (Decimal("3.5"), "3.5 نجمة"),
                            (Decimal("4.0"), "4.0 نجمة"),
                            (Decimal("4.5"), "4.5 نجمة"),
                            (Decimal("5.0"), "5.0 نجمة"),
                        ],
                        decimal_places=1,
                        help_text="choose the rating of the game",
                        max_digits=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_ratings",
                "unique_together": {("product", "user")},
            },
        ),
    ]
