# Generated by Django 4.2 on 2025-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_productrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="games_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
