# Generated by Django 4.2 on 2025-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_product_games_type_product_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="games_type",
            field=models.CharField(
                blank=True,
                choices=[("offline", "Offline"), ("online", "Online")],
                max_length=255,
                null=True,
            ),
        ),
    ]
