# Generated by Django 4.2 on 2025-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_alter_product_games_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="the percentage of discount on the product",
                max_digits=5,
            ),
        ),
    ]
