# Generated by Django 4.2 on 2025-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="the percentage of discount on the product",
                max_digits=5,
            ),
        ),
    ]
