# Generated by Django 4.2 on 2025-03-17 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_alter_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrating",
            name="rating",
            field=models.DecimalField(
                choices=[
                    (Decimal("1.0"), "1.0 "),
                    (Decimal("1.5"), "1.5 "),
                    (Decimal("2.0"), "2.0 "),
                    (Decimal("2.5"), "2.5 "),
                    (Decimal("3.0"), "3.0 "),
                    (Decimal("3.5"), "3.5 "),
                    (Decimal("4.0"), "4.0 "),
                    (Decimal("4.5"), "4.5 "),
                    (Decimal("5.0"), "5.0 "),
                ],
                decimal_places=1,
                help_text="choose the rating of the game",
                max_digits=2,
            ),
        ),
    ]
